-- CommonGround — every migration, in order, as one script.
--
-- GENERATED by supabase/build_apply_all.sh. Do not edit by hand;
-- edit the migration and regenerate, or the two will drift apart.
--
-- SAFE TO RUN MORE THAN ONCE. Every statement is idempotent
-- (create ... if not exists / drop ... if exists / create or replace),
-- so it does not matter which migrations your project already has.
-- Running it on a fully migrated project changes nothing.
--
-- It does NOT run inside a single transaction: the Supabase SQL Editor
-- wraps each statement itself. If it stops partway, fix the reported
-- error and run the whole thing again — that is what idempotency buys.
--
-- Generated from:
--   20260724000001_init.sql
--   20260725000002_groups.sql
--   20260727000003_trust.sql
--   20260727000004_corroboration.sql
--   20260728000005_moderation.sql
--   20260728000006_signing_keys.sql
--   20260730000007_join_hardening.sql


-- ============================================================
-- 20260724000001_init.sql
-- ============================================================

-- CommonGround initial schema (E5/E8).
-- Security model (SECURITY.md): RLS deny-by-default on every table; the
-- publishable key grants nothing by itself. All privileged writes go through
-- SECURITY DEFINER functions that check the admin role from JWT app_metadata
-- (server-set, never client-writable). Clients send client-generated ids for
-- idempotent sync retries.

-- ---------------------------------------------------------------- helpers

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select coalesce(
    (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin',
    false
  );
$$;

-- ------------------------------------------------------------------ tables

create table if not exists public.facilities (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 120),
  type text not null check (
    type in ('water','food','shelter','medical','toilet','safeArea','danger')
  ),
  status text not null check (status in ('good','low','out','closed')),
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180),
  canonical boolean not null default true,
  verified_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.capacity_readings (
  id uuid primary key default gen_random_uuid(),
  facility_id uuid not null references public.facilities(id) on delete cascade,
  resource text not null check (resource in ('water','food','shelter')),
  for_people integer not null check (for_people between 0 and 1000000),
  verified_by uuid references auth.users(id),
  verified_at timestamptz,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists capacity_readings_facility_idx
  on public.capacity_readings(facility_id, created_at desc);

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  -- Client-generated id: makes offline sync retries idempotent.
  client_id text not null unique check (char_length(client_id) <= 64),
  -- Text reference (not FK): clients may reference facilities they only
  -- know locally; the admin decision function resolves it server-side.
  facility_ref text check (char_length(facility_ref) <= 64),
  lat double precision check (lat between -90 and 90),
  lng double precision check (lng between -180 and 180),
  payload jsonb not null,
  submitter_id uuid not null default auth.uid() references auth.users(id),
  state text not null default 'pending'
    check (state in ('pending','approved','rejected')),
  reason text check (char_length(reason) <= 500),
  created_at timestamptz not null default now()
);
create index if not exists submissions_pending_idx
  on public.submissions(state, created_at) where state = 'pending';

create table if not exists public.alerts (
  id uuid primary key default gen_random_uuid(),
  severity text not null check (severity in ('info','warn','critical')),
  body text not null check (char_length(body) between 1 and 500),
  lat double precision check (lat between -90 and 90),
  lng double precision check (lng between -180 and 180),
  radius_meters double precision check (radius_meters between 0 and 100000),
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create table if not exists public.sos_signals (
  id uuid primary key default gen_random_uuid(),
  client_id text not null unique check (char_length(client_id) <= 64),
  fired_at timestamptz not null,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now()
);

-- Append-only; writes happen inside SECURITY DEFINER functions only.
create table if not exists public.audit_log (
  id bigint generated always as identity primary key,
  actor_id uuid,
  action text not null,
  entity text,
  entity_id text,
  before jsonb,
  after jsonb,
  ts timestamptz not null default now()
);

-- --------------------------------------------------------------------- RLS
-- Enabling RLS with no policy = deny. Policies below are the ONLY access.

alter table public.facilities enable row level security;
alter table public.capacity_readings enable row level security;
alter table public.submissions enable row level security;
alter table public.alerts enable row level security;
alter table public.sos_signals enable row level security;
alter table public.audit_log enable row level security;

-- Public verified map: anyone (including signed-out) can read.
drop policy if exists facilities_read on public.facilities;
create policy facilities_read on public.facilities
  for select to anon, authenticated using (true);

drop policy if exists capacity_read on public.capacity_readings;
create policy capacity_read on public.capacity_readings
  for select to anon, authenticated using (true);

drop policy if exists alerts_read on public.alerts;
create policy alerts_read on public.alerts
  for select to anon, authenticated using (true);

-- Submissions: users insert their own pending rows and read only their own;
-- admins read all. State changes ONLY via the decision functions below.
drop policy if exists submissions_insert_own on public.submissions;
create policy submissions_insert_own on public.submissions
  for insert to authenticated
  with check (submitter_id = auth.uid() and state = 'pending');

drop policy if exists submissions_read_own on public.submissions;
create policy submissions_read_own on public.submissions
  for select to authenticated
  using (submitter_id = auth.uid() or public.is_admin());

-- Alerts: only admins broadcast.
drop policy if exists alerts_admin_insert on public.alerts;
create policy alerts_admin_insert on public.alerts
  for insert to authenticated
  with check (public.is_admin());

-- SOS: users file their own; only admins see them.
drop policy if exists sos_insert_own on public.sos_signals;
create policy sos_insert_own on public.sos_signals
  for insert to authenticated
  with check (created_by = auth.uid());

drop policy if exists sos_admin_read on public.sos_signals;
create policy sos_admin_read on public.sos_signals
  for select to authenticated
  using (public.is_admin());

-- Audit log: admins read; nobody writes directly (functions only).
drop policy if exists audit_admin_read on public.audit_log;
create policy audit_admin_read on public.audit_log
  for select to authenticated
  using (public.is_admin());

-- --------------------------------------------- admin decision functions
-- SECURITY DEFINER so they can write across tables; each one re-checks
-- is_admin() — never trust the caller.

create or replace function public.approve_submission(
  p_submission_id uuid,
  p_mark_verified boolean default true,
  p_capacity_ttl_minutes integer default 45
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  sub public.submissions%rowtype;
  target_facility uuid;
  v_category text;
  v_status text;
  v_for_people integer;
begin
  if not public.is_admin() then
    raise exception 'admin role required';
  end if;

  select * into sub from public.submissions
    where id = p_submission_id and state = 'pending'
    for update;
  if not found then
    raise exception 'pending submission not found';
  end if;

  v_category := sub.payload ->> 'category';
  v_status := coalesce(sub.payload ->> 'status', 'good');
  v_for_people := (sub.payload ->> 'forPeople')::integer;

  -- Resolve the referenced facility if the client sent a valid uuid.
  if sub.facility_ref is not null then
    begin
      select id into target_facility from public.facilities
        where id = sub.facility_ref::uuid;
    exception when invalid_text_representation then
      target_facility := null;
    end;
  end if;

  if target_facility is null then
    insert into public.facilities (name, type, status, lat, lng, verified_at)
    values (
      coalesce(
        nullif(sub.payload ->> 'name', ''),
        initcap(v_category) || ' (reported)'
      ),
      v_category,
      v_status,
      sub.lat,
      sub.lng,
      case when p_mark_verified then now() end
    )
    returning id into target_facility;
  else
    update public.facilities
      set status = v_status,
          verified_at = case when p_mark_verified then now()
                             else verified_at end,
          updated_at = now()
      where id = target_facility;
  end if;

  if v_for_people is not null and v_category in ('water','food','shelter') then
    insert into public.capacity_readings
      (facility_id, resource, for_people, verified_by, verified_at, expires_at)
    values (
      target_facility,
      v_category,
      v_for_people,
      auth.uid(),
      case when p_mark_verified then now() end,
      now() + make_interval(mins => p_capacity_ttl_minutes)
    );
  end if;

  update public.submissions
    set state = 'approved'
    where id = p_submission_id;

  insert into public.audit_log (actor_id, action, entity, entity_id, before, after)
  values (
    auth.uid(), 'approve_submission', 'submission', p_submission_id::text,
    jsonb_build_object('state', 'pending'),
    jsonb_build_object('state', 'approved', 'facility_id', target_facility)
  );
end;
$$;

create or replace function public.reject_submission(
  p_submission_id uuid,
  p_reason text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'admin role required';
  end if;
  if p_reason is null or char_length(trim(p_reason)) = 0 then
    raise exception 'reason required';
  end if;

  update public.submissions
    set state = 'rejected', reason = p_reason
    where id = p_submission_id and state = 'pending';
  if not found then
    raise exception 'pending submission not found';
  end if;

  insert into public.audit_log (actor_id, action, entity, entity_id, before, after)
  values (
    auth.uid(), 'reject_submission', 'submission', p_submission_id::text,
    jsonb_build_object('state', 'pending'),
    jsonb_build_object('state', 'rejected', 'reason', p_reason)
  );
end;
$$;

-- Only signed-in users may call the decision functions (they re-check admin).
revoke execute on function public.approve_submission from public, anon;
revoke execute on function public.reject_submission from public, anon;
grant execute on function public.approve_submission to authenticated;
grant execute on function public.reject_submission to authenticated;

-- ============================================================
-- 20260725000002_groups.sql
-- ============================================================

-- CommonGround groups + end-to-end encrypted chat (Phase 3 / ADR-16).
-- Security: RLS deny-by-default. Only active members can read a group's rows.
-- The server stores ONLY public keys, sealed key envelopes, and message
-- ciphertext — never a group key or plaintext.
--
-- Order matters: tables first, then the `language sql` helper functions
-- (validated at creation time, so they must see the tables), then RLS
-- policies (which call the helpers).

-- ------------------------------------------------------------------------ tables

-- Each user's X25519 public key (for sealing group keys to them). Public keys
-- only — private keys never leave the device.
create table if not exists public.device_keys (
  user_id uuid primary key default auth.uid() references auth.users(id),
  public_key text not null check (char_length(public_key) <= 128),
  updated_at timestamptz not null default now()
);

create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 80),
  description text check (char_length(description) <= 500),
  visibility text not null default 'hidden' check (visibility in ('public','hidden')),
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id),
  role text not null default 'member' check (role in ('admin','member')),
  state text not null default 'pending' check (state in ('pending','active','banned')),
  display_name text check (char_length(display_name) <= 60),
  joined_via text check (char_length(joined_via) <= 40),
  created_at timestamptz not null default now(),
  primary key (group_id, user_id)
);
create index if not exists group_members_user_idx on public.group_members(user_id, state);

-- The group key, sealed (ECIES) to one member's device key. Epoch supports
-- future key rotation on membership change.
create table if not exists public.group_key_envelopes (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  member_user_id uuid not null references auth.users(id),
  key_epoch integer not null default 1,
  sealed text not null,
  created_at timestamptz not null default now(),
  unique (group_id, member_user_id, key_epoch)
);
create index if not exists group_envelopes_member_idx
  on public.group_key_envelopes(member_user_id, group_id);

create table if not exists public.group_invites (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  code text not null unique check (char_length(code) between 6 and 64),
  expires_at timestamptz not null,
  max_uses integer not null default 10 check (max_uses between 1 and 1000),
  uses integer not null default 0,
  revoked boolean not null default false,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now()
);

-- Group-private pins ("amenities": meeting points, supplies). Never promotable
-- to the public map; enforced here at the DB layer, not just the UI.
create table if not exists public.group_pins (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  type text not null check (type in ('meeting','supply','medical','water','food','custom')),
  label text not null check (char_length(label) <= 80),
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180),
  note text check (char_length(note) <= 300),
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

-- E2E chat: ciphertext only (AES-GCM under the group key).
create table if not exists public.group_messages (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  sender_id uuid not null default auth.uid() references auth.users(id),
  ciphertext text not null,
  key_epoch integer not null default 1,
  created_at timestamptz not null default now()
);
create index if not exists group_messages_group_idx on public.group_messages(group_id, created_at);

-- ------------------------------------------------------------- membership helpers
-- Created after the tables they read (language sql = validated at creation).

create or replace function public.is_group_member(g uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(
    select 1 from public.group_members
    where group_id = g and user_id = auth.uid() and state = 'active'
  );
$$;

create or replace function public.is_group_admin(g uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(
    select 1 from public.group_members
    where group_id = g and user_id = auth.uid()
      and state = 'active' and role = 'admin'
  );
$$;

-- --------------------------------------------------------------------------- RLS

alter table public.device_keys enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.group_key_envelopes enable row level security;
alter table public.group_invites enable row level security;
alter table public.group_pins enable row level security;
alter table public.group_messages enable row level security;

-- device_keys: anyone signed in can read a public key (needed to seal to it);
-- a user writes only their own.
drop policy if exists device_keys_read on public.device_keys;
create policy device_keys_read on public.device_keys
  for select to authenticated using (true);
drop policy if exists device_keys_upsert on public.device_keys;
create policy device_keys_upsert on public.device_keys
  for insert to authenticated with check (user_id = auth.uid());
drop policy if exists device_keys_update on public.device_keys;
create policy device_keys_update on public.device_keys
  for update to authenticated using (user_id = auth.uid());

-- groups: members read; public groups are discoverable; creator inserts.
drop policy if exists groups_read on public.groups;
create policy groups_read on public.groups
  for select to authenticated
  using (visibility = 'public' or public.is_group_member(id));
drop policy if exists groups_insert on public.groups;
create policy groups_insert on public.groups
  for insert to authenticated with check (created_by = auth.uid());
drop policy if exists groups_admin_update on public.groups;
create policy groups_admin_update on public.groups
  for update to authenticated using (public.is_group_admin(id));

-- group_members: a member sees the roster of groups they belong to; a user can
-- insert their OWN pending row (join request) or the creator seeds admin.
drop policy if exists members_read on public.group_members;
create policy members_read on public.group_members
  for select to authenticated
  using (user_id = auth.uid() or public.is_group_member(group_id));
drop policy if exists members_self_join on public.group_members;
create policy members_self_join on public.group_members
  for insert to authenticated with check (user_id = auth.uid());
drop policy if exists members_admin_manage on public.group_members;
create policy members_admin_manage on public.group_members
  for update to authenticated using (public.is_group_admin(group_id));
drop policy if exists members_admin_delete on public.group_members;
create policy members_admin_delete on public.group_members
  for delete to authenticated using (public.is_group_admin(group_id));

-- envelopes: a member reads envelopes sealed to them; admins create them.
drop policy if exists envelopes_read_own on public.group_key_envelopes;
create policy envelopes_read_own on public.group_key_envelopes
  for select to authenticated using (member_user_id = auth.uid());
drop policy if exists envelopes_admin_insert on public.group_key_envelopes;
create policy envelopes_admin_insert on public.group_key_envelopes
  for insert to authenticated with check (public.is_group_admin(group_id));

-- invites: members read; admins manage.
drop policy if exists invites_member_read on public.group_invites;
create policy invites_member_read on public.group_invites
  for select to authenticated using (public.is_group_member(group_id));
drop policy if exists invites_admin_insert on public.group_invites;
create policy invites_admin_insert on public.group_invites
  for insert to authenticated with check (public.is_group_admin(group_id));
drop policy if exists invites_admin_update on public.group_invites;
create policy invites_admin_update on public.group_invites
  for update to authenticated using (public.is_group_admin(group_id));

-- pins: members read/write within their group.
drop policy if exists pins_member_read on public.group_pins;
create policy pins_member_read on public.group_pins
  for select to authenticated using (public.is_group_member(group_id));
drop policy if exists pins_member_insert on public.group_pins;
create policy pins_member_insert on public.group_pins
  for insert to authenticated with check (public.is_group_member(group_id));
drop policy if exists pins_admin_delete on public.group_pins;
create policy pins_admin_delete on public.group_pins
  for delete to authenticated using (public.is_group_admin(group_id));

-- messages: members read all group messages and send as themselves.
drop policy if exists messages_member_read on public.group_messages;
create policy messages_member_read on public.group_messages
  for select to authenticated using (public.is_group_member(group_id));
drop policy if exists messages_member_send on public.group_messages;
create policy messages_member_send on public.group_messages
  for insert to authenticated
  with check (public.is_group_member(group_id) and sender_id = auth.uid());

-- Look up a group by invite code for the join flow (SECURITY DEFINER: reads
-- the invite without exposing the whole table; validates expiry/uses/revoked).
create or replace function public.resolve_invite(p_code text)
returns table(group_id uuid, group_name text)
language plpgsql security definer set search_path = public as $$
begin
  return query
  select g.id, g.name
  from public.group_invites i
  join public.groups g on g.id = i.group_id
  where i.code = p_code
    and not i.revoked
    and i.expires_at > now()
    and i.uses < i.max_uses;
end;
$$;

revoke execute on function public.resolve_invite from public, anon;
grant execute on function public.resolve_invite to authenticated;

-- ============================================================
-- 20260727000003_trust.sql
-- ============================================================

-- Phase 4 — trust scores and promotion rules (ADR-25).
--
-- The problem this solves is the top live risk in PROJECT_MANAGEMENT.md:
-- verification is a single-admin bottleneck, and during an actual protest a
-- queue that nobody drains is the same as no map at all.
--
-- The shape of the answer matters more than the numbers. A promoted
-- "verifier" is deliberately NOT a small admin:
--   * they can only approve UPDATES to facilities that already exist —
--     never create a new pin, so the worst case is a status flip on a known
--     facility, which the next report corrects;
--   * their approvals publish with verified_at = NULL, i.e. visible but not
--     admin-verified. This is exactly what ADR-2's two-axis model (publish
--     status ⊥ verified flag) was built for;
--   * they cannot decide their own submissions;
--   * they cannot REJECT anything. Rejection is admin-only on purpose: an
--     approval is self-correcting (the map keeps receiving reports), while a
--     rejection silently removes information from the queue, which is the
--     move a hostile verifier would make;
--   * they are rate-limited, so a compromised account cannot sweep the queue;
--   * every decision is in audit_log with the actor id, same as an admin's.
--
-- Trust is also REVERSIBLE. Counters recompute the tier on every decision, so
-- an account that builds standing and then starts posting garbage loses it
-- without an admin intervening.

-- ----------------------------------------------------------------- table

create table if not exists public.user_trust (
  user_id uuid primary key references auth.users(id) on delete cascade,
  approved_count integer not null default 0 check (approved_count >= 0),
  rejected_count integer not null default 0 check (rejected_count >= 0),
  tier text not null default 'new' check (tier in ('new','trusted','verifier')),
  promoted_at timestamptz,
  updated_at timestamptz not null default now()
);

-- Deny-by-default: RLS on, and the ONLY policy is a read of your own row
-- (plus admin read). There is no insert/update/delete policy anywhere, so
-- nobody can promote themselves — writes exist only inside the SECURITY
-- DEFINER functions below.
alter table public.user_trust enable row level security;

drop policy if exists trust_read_own on public.user_trust;
drop policy if exists trust_read_own on public.user_trust;
create policy trust_read_own on public.user_trust
  for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

-- --------------------------------------------------------------- thresholds
-- Kept in one function so the app can render the same numbers it is judged
-- by, instead of hardcoding a copy that silently drifts.

create or replace function public.trust_thresholds()
returns jsonb
language sql
immutable
as $$
  select jsonb_build_object(
    'trusted_approved', 5,
    'verifier_approved', 20,
    -- Accuracy gates: approvals must outnumber rejections by this factor.
    -- A high-volume account that is wrong a lot never reaches verifier.
    'trusted_ratio', 4,
    'verifier_ratio', 9,
    'verifier_hourly_limit', 30
  );
$$;

-- Explicit ordering. Never compare tier names as text — 'new' < 'trusted' <
-- 'verifier' happens to sort correctly today and would silently invert the
-- moment a tier is renamed.
create or replace function public.trust_rank(p_tier text)
returns integer
language sql
immutable
as $$
  select case p_tier
    when 'verifier' then 2
    when 'trusted' then 1
    else 0
  end;
$$;

create or replace function public.trust_tier_for(
  p_approved integer,
  p_rejected integer
)
returns text
language sql
immutable
as $$
  select case
    when p_approved >= 20 and p_approved >= 9 * p_rejected then 'verifier'
    when p_approved >= 5  and p_approved >= 4 * p_rejected then 'trusted'
    else 'new'
  end;
$$;

-- ------------------------------------------------------------- bookkeeping
-- Internal: called by the decision functions, never by a client.

create or replace function public.bump_trust(
  p_user uuid,
  p_approved boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  old_tier text;
  new_tier text;
  a integer;
  r integer;
begin
  if p_user is null then
    return;
  end if;

  insert into public.user_trust (user_id) values (p_user)
    on conflict (user_id) do nothing;

  update public.user_trust
    set approved_count = approved_count + case when p_approved then 1 else 0 end,
        rejected_count = rejected_count + case when p_approved then 0 else 1 end,
        updated_at = now()
    where user_id = p_user
    returning tier, approved_count, rejected_count into old_tier, a, r;

  new_tier := public.trust_tier_for(a, r);
  if new_tier is distinct from old_tier then
    update public.user_trust
      set tier = new_tier,
          promoted_at = case
            when new_tier <> 'new' then now() else null end
      where user_id = p_user;

    -- Promotions AND demotions are audited: a change in who can publish is
    -- exactly the kind of event that must be reconstructible after the fact.
    insert into public.audit_log
      (actor_id, action, entity, entity_id, before, after)
    values (
      null,
      case when public.trust_rank(new_tier) > public.trust_rank(old_tier)
           then 'promote_user' else 'demote_user' end,
      'user', p_user::text,
      jsonb_build_object('tier', old_tier),
      jsonb_build_object('tier', new_tier, 'approved', a, 'rejected', r)
    );
  end if;
end;
$$;

revoke execute on function public.bump_trust(uuid, boolean) from public, anon, authenticated;

-- ------------------------------------------------------------ verifier gate

create or replace function public.is_verifier()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select tier = 'verifier' from public.user_trust where user_id = auth.uid()),
    false
  );
$$;

grant execute on function public.is_verifier() to authenticated;

-- Your own standing, including the thresholds you are measured against.
-- An RPC rather than a plain select because most users have no row yet and a
-- missing row must read as "new", not as an error or an empty screen.
create or replace function public.my_trust()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'tier', coalesce(t.tier, 'new'),
    'approved', coalesce(t.approved_count, 0),
    'rejected', coalesce(t.rejected_count, 0),
    'thresholds', public.trust_thresholds()
  )
  from (select 1) one
  left join public.user_trust t on t.user_id = auth.uid();
$$;

revoke execute on function public.my_trust() from public, anon;
grant execute on function public.my_trust() to authenticated;

-- --------------------------------------------- decision functions, extended

create or replace function public.approve_submission(
  p_submission_id uuid,
  p_mark_verified boolean default true,
  p_capacity_ttl_minutes integer default 45
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  sub public.submissions%rowtype;
  target_facility uuid;
  v_category text;
  v_status text;
  v_for_people integer;
  v_admin boolean;
  v_recent integer;
begin
  v_admin := public.is_admin();
  if not (v_admin or public.is_verifier()) then
    raise exception 'admin or verifier role required';
  end if;

  select * into sub from public.submissions
    where id = p_submission_id and state = 'pending'
    for update;
  if not found then
    raise exception 'pending submission not found';
  end if;

  -- Verifier restrictions. Checked server-side because a client-side check
  -- is not a check (SECURITY.md).
  if not v_admin then
    if sub.submitter_id = auth.uid() then
      raise exception 'verifiers cannot decide their own submissions';
    end if;

    select count(*) into v_recent from public.audit_log
      where actor_id = auth.uid()
        and action = 'approve_submission'
        and ts > now() - interval '1 hour';
    if v_recent >= (public.trust_thresholds() ->> 'verifier_hourly_limit')::int
    then
      raise exception 'verifier hourly approval limit reached';
    end if;

    -- A verifier approval never carries the admin-verified flag.
    p_mark_verified := false;
  end if;

  v_category := sub.payload ->> 'category';
  v_status := coalesce(sub.payload ->> 'status', 'good');
  v_for_people := (sub.payload ->> 'forPeople')::integer;

  -- Resolve the referenced facility if the client sent a valid uuid.
  if sub.facility_ref is not null then
    begin
      select id into target_facility from public.facilities
        where id = sub.facility_ref::uuid;
    exception when invalid_text_representation then
      target_facility := null;
    end;
  end if;

  -- Creating a pin on the canonical public map stays an admin act: a wrong
  -- status on a known facility gets corrected by the next report, a
  -- fabricated facility does not.
  if target_facility is null and not v_admin then
    raise exception 'verifiers cannot create new facilities';
  end if;

  if target_facility is null then
    insert into public.facilities (name, type, status, lat, lng, verified_at)
    values (
      coalesce(
        nullif(sub.payload ->> 'name', ''),
        initcap(v_category) || ' (reported)'
      ),
      v_category,
      v_status,
      sub.lat,
      sub.lng,
      case when p_mark_verified then now() end
    )
    returning id into target_facility;
  else
    update public.facilities
      set status = v_status,
          verified_at = case when p_mark_verified then now()
                             else verified_at end,
          updated_at = now()
      where id = target_facility;
  end if;

  if v_for_people is not null and v_category in ('water','food','shelter') then
    insert into public.capacity_readings
      (facility_id, resource, for_people, verified_by, verified_at, expires_at)
    values (
      target_facility,
      v_category,
      v_for_people,
      auth.uid(),
      case when p_mark_verified then now() end,
      now() + make_interval(mins => p_capacity_ttl_minutes)
    );
  end if;

  update public.submissions
    set state = 'approved'
    where id = p_submission_id;

  insert into public.audit_log (actor_id, action, entity, entity_id, before, after)
  values (
    auth.uid(), 'approve_submission', 'submission', p_submission_id::text,
    jsonb_build_object('state', 'pending'),
    jsonb_build_object(
      'state', 'approved',
      'facility_id', target_facility,
      'by', case when v_admin then 'admin' else 'verifier' end
    )
  );

  -- Credit the SUBMITTER, not the decider.
  perform public.bump_trust(sub.submitter_id, true);
end;
$$;

create or replace function public.reject_submission(
  p_submission_id uuid,
  p_reason text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_submitter uuid;
begin
  -- Admin-only, unchanged: see the header note on why verifiers may approve
  -- but never reject.
  if not public.is_admin() then
    raise exception 'admin role required';
  end if;
  if p_reason is null or char_length(trim(p_reason)) = 0 then
    raise exception 'reason required';
  end if;

  update public.submissions
    set state = 'rejected', reason = p_reason
    where id = p_submission_id and state = 'pending'
    returning submitter_id into v_submitter;
  if not found then
    raise exception 'pending submission not found';
  end if;

  insert into public.audit_log (actor_id, action, entity, entity_id, before, after)
  values (
    auth.uid(), 'reject_submission', 'submission', p_submission_id::text,
    jsonb_build_object('state', 'pending'),
    jsonb_build_object('state', 'rejected', 'reason', p_reason)
  );

  perform public.bump_trust(v_submitter, false);
end;
$$;

revoke execute on function public.approve_submission from public, anon;
revoke execute on function public.reject_submission from public, anon;
grant execute on function public.approve_submission to authenticated;
grant execute on function public.reject_submission to authenticated;

-- ============================================================
-- 20260727000004_corroboration.sql
-- ============================================================

-- Phase 4 — corroboration auto-verify (ADR-26).
--
-- The other half of the bottleneck fix. Trust promotion (ADR-25) adds more
-- people who can approve; corroboration handles the case where nobody is
-- available at all: when several independent, already-trusted reporters
-- agree that a known facility is in the same state, that agreement publishes
-- on its own.
--
-- The whole risk here is sock puppets: anonymous sign-in is free, so "three
-- users agree" is worth nothing by itself. Three defences:
--   1. Only submissions from accounts at tier 'trusted' or better count, and
--      that tier costs five admin-approved reports EACH to reach.
--   2. Corroborated approvals do NOT credit trust. Otherwise a ring of three
--      trusted accounts could corroborate each other up to verifier without
--      an admin ever seeing them again.
--   3. It can only change the status of a facility that ALREADY exists, and
--      never sets verified_at — the same envelope a verifier gets.
-- Worst case is therefore a status flip on a known pin, corrected by the next
-- report, and the audit row names every submitter involved.

create or replace function public.corroboration_settings()
returns jsonb
language sql
immutable
as $$
  select jsonb_build_object(
    'min_reports', 3,
    'window_minutes', 20
  );
$$;

create or replace function public.try_corroborate()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_facility uuid;
  v_status text;
  v_window interval;
  v_min integer;
  v_agreeing integer;
  v_submitters uuid[];
begin
  -- Only a pending report against an existing facility, carrying a status.
  if new.state <> 'pending' or new.facility_ref is null then
    return new;
  end if;
  v_status := new.payload ->> 'status';
  if v_status is null then
    return new;
  end if;

  begin
    select id into v_facility from public.facilities
      where id = new.facility_ref::uuid;
  exception when invalid_text_representation then
    return new;
  end;
  if v_facility is null then
    return new;
  end if;

  v_min := (public.corroboration_settings() ->> 'min_reports')::int;
  v_window := make_interval(
    mins => (public.corroboration_settings() ->> 'window_minutes')::int
  );

  -- Distinct trusted submitters agreeing on the same facility AND the same
  -- status inside the window. Distinct on submitter, so one account filing
  -- the same report three times corroborates nothing.
  select array_agg(distinct s.submitter_id) into v_submitters
  from public.submissions s
  join public.user_trust t on t.user_id = s.submitter_id
  where s.facility_ref = new.facility_ref
    and s.state = 'pending'
    and (s.payload ->> 'status') = v_status
    and s.created_at > now() - v_window
    and t.tier in ('trusted', 'verifier');

  v_agreeing := coalesce(array_length(v_submitters, 1), 0);
  if v_agreeing < v_min then
    return new;
  end if;

  -- Publish, but never as admin-verified (ADR-2's second axis).
  update public.facilities
    set status = v_status,
        updated_at = now()
    where id = v_facility;

  update public.submissions s
    set state = 'approved'
    where s.facility_ref = new.facility_ref
      and s.state = 'pending'
      and (s.payload ->> 'status') = v_status
      and s.created_at > now() - v_window
      and s.submitter_id = any(v_submitters);

  -- actor_id is null: no human decided this. The submitters are named so the
  -- decision is still reconstructible — and so a colluding ring is visible.
  insert into public.audit_log
    (actor_id, action, entity, entity_id, before, after)
  values (
    null, 'corroborate_submission', 'facility', v_facility::text,
    jsonb_build_object('status', 'pending'),
    jsonb_build_object(
      'status', v_status,
      'reports', v_agreeing,
      'submitters', to_jsonb(v_submitters)
    )
  );

  -- Deliberately NO bump_trust here: corroboration must not be a path to
  -- promotion, or a ring of trusted accounts could farm each other.
  return new;
end;
$$;

drop trigger if exists submissions_corroborate on public.submissions;
create trigger submissions_corroborate
  after insert on public.submissions
  for each row execute function public.try_corroborate();

-- ============================================================
-- 20260728000005_moderation.sql
-- ============================================================

-- Phase 4 — moderator tooling (ADR-27).
--
-- Trust promotion (ADR-25) is automatic, and automatic promotion needs a
-- manual brake. The counters only demote an account that gets things
-- *wrong*; they say nothing about an account that is accurate and hostile —
-- an infiltrator who reports true facts to build standing, then waits. An
-- admin has to be able to take the badge back that same minute, without
-- waiting for arithmetic.
--
-- Two functions, both admin-only, both audited:
--   * revoke_verifier  — drops an account to 'new' and HOLDS it there;
--   * restore_trust    — lifts the hold and recomputes from the counters.
--
-- The hold is the important half. Without it, revocation lasts exactly until
-- the next approved submission recomputes the tier and hands the badge
-- straight back.

alter table public.user_trust
  add column if not exists held boolean not null default false,
  add column if not exists hold_reason text
    check (char_length(hold_reason) <= 500);

-- A held account never gets promoted by the automatic path. bump_trust keeps
-- counting (so the record stays honest) but stops re-tiering.
create or replace function public.bump_trust(
  p_user uuid,
  p_approved boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  old_tier text;
  new_tier text;
  a integer;
  r integer;
  v_held boolean;
begin
  if p_user is null then
    return;
  end if;

  insert into public.user_trust (user_id) values (p_user)
    on conflict (user_id) do nothing;

  update public.user_trust
    set approved_count = approved_count + case when p_approved then 1 else 0 end,
        rejected_count = rejected_count + case when p_approved then 0 else 1 end,
        updated_at = now()
    where user_id = p_user
    returning tier, approved_count, rejected_count, held
    into old_tier, a, r, v_held;

  -- Counts still move; standing does not. An admin's hold outranks the
  -- arithmetic until an admin lifts it.
  if v_held then
    return;
  end if;

  new_tier := public.trust_tier_for(a, r);
  if new_tier is distinct from old_tier then
    update public.user_trust
      set tier = new_tier,
          promoted_at = case
            when new_tier <> 'new' then now() else null end
      where user_id = p_user;

    insert into public.audit_log
      (actor_id, action, entity, entity_id, before, after)
    values (
      null,
      case when public.trust_rank(new_tier) > public.trust_rank(old_tier)
           then 'promote_user' else 'demote_user' end,
      'user', p_user::text,
      jsonb_build_object('tier', old_tier),
      jsonb_build_object('tier', new_tier, 'approved', a, 'rejected', r)
    );
  end if;
end;
$$;

revoke execute on function public.bump_trust(uuid, boolean) from public, anon, authenticated;

-- A held account is not a verifier, whatever the tier column says.
create or replace function public.is_verifier()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select tier = 'verifier' and not held
       from public.user_trust where user_id = auth.uid()),
    false
  );
$$;

grant execute on function public.is_verifier() to authenticated;

create or replace function public.revoke_verifier(
  p_user uuid,
  p_reason text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  old_tier text;
begin
  if not public.is_admin() then
    raise exception 'admin role required';
  end if;
  if p_reason is null or char_length(trim(p_reason)) = 0 then
    raise exception 'reason required';
  end if;
  -- An admin removing their own standing is almost certainly a mistake, and
  -- the admin role does not come from this table anyway.
  if p_user = auth.uid() then
    raise exception 'cannot revoke your own standing';
  end if;

  insert into public.user_trust (user_id) values (p_user)
    on conflict (user_id) do nothing;

  update public.user_trust
    set tier = 'new',
        held = true,
        hold_reason = p_reason,
        promoted_at = null,
        updated_at = now()
    where user_id = p_user
    returning tier into old_tier;

  insert into public.audit_log
    (actor_id, action, entity, entity_id, before, after)
  values (
    auth.uid(), 'revoke_verifier', 'user', p_user::text,
    jsonb_build_object('tier', old_tier),
    jsonb_build_object('tier', 'new', 'held', true, 'reason', p_reason)
  );
end;
$$;

create or replace function public.restore_trust(p_user uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  a integer;
  r integer;
  new_tier text;
begin
  if not public.is_admin() then
    raise exception 'admin role required';
  end if;

  update public.user_trust
    set held = false, hold_reason = null, updated_at = now()
    where user_id = p_user
    returning approved_count, rejected_count into a, r;
  if not found then
    raise exception 'no standing to restore';
  end if;

  -- Lifting the hold recomputes from the record rather than restoring the
  -- old badge: the counters are the source of truth again.
  new_tier := public.trust_tier_for(a, r);
  update public.user_trust
    set tier = new_tier,
        promoted_at = case when new_tier <> 'new' then now() end
    where user_id = p_user;

  insert into public.audit_log
    (actor_id, action, entity, entity_id, before, after)
  values (
    auth.uid(), 'restore_trust', 'user', p_user::text,
    jsonb_build_object('held', true),
    jsonb_build_object('held', false, 'tier', new_tier)
  );
end;
$$;

revoke execute on function public.revoke_verifier from public, anon;
revoke execute on function public.restore_trust from public, anon;
grant execute on function public.revoke_verifier to authenticated;
grant execute on function public.restore_trust to authenticated;

-- Per-reporter history for the moderator screen. An admin can already read
-- every submission and every trust row by RLS; this only assembles them, so
-- it is SECURITY INVOKER — the caller's own permissions still apply and a
-- non-admin gets their own record, not someone else's.
create or replace function public.reporter_history(p_user uuid)
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'tier', coalesce((select tier from public.user_trust where user_id = p_user), 'new'),
    'held', coalesce((select held from public.user_trust where user_id = p_user), false),
    'hold_reason', (select hold_reason from public.user_trust where user_id = p_user),
    'approved', coalesce((select approved_count from public.user_trust where user_id = p_user), 0),
    'rejected', coalesce((select rejected_count from public.user_trust where user_id = p_user), 0),
    'recent', coalesce((
      select jsonb_agg(row_to_json(s))
      from (
        select id, state, reason, created_at, payload ->> 'category' as category,
               payload ->> 'status' as status
        from public.submissions
        where submitter_id = p_user
        order by created_at desc
        limit 20
      ) s
    ), '[]'::jsonb)
  );
$$;

revoke execute on function public.reporter_history from public, anon;
grant execute on function public.reporter_history to authenticated;

-- ============================================================
-- 20260728000006_signing_keys.sql
-- ============================================================

-- Cryptographic sender attribution for group messages (ADR-29).
--
-- Until now, who sent a group message was attested by the SERVER: the RLS
-- policy `messages_member_send` enforces `sender_id = auth.uid()` on insert.
-- That is a real control, but it is the server's word, and it is the one
-- guarantee that does not survive the server going away — which is exactly
-- the case the offline Wi-Fi transport analysis is aimed at
-- (`docs/research/offline-wifi-transport.md`).
--
-- Messages are encrypted with AES-GCM under a key SHARED by the whole group.
-- That proves a message came from someone holding the group key; it does not
-- prove which member. So without a signature, any group member could
-- originate a message attributed to any other member the moment the transport
-- is not a server that stamps sender_id. In this app the plausible attack is
-- a forged "the medical tent has moved" from a trusted organiser.
--
-- Fix: each device publishes an Ed25519 signing public key alongside its
-- X25519 identity key, and signs (group, epoch, ciphertext). Two keys because
-- an X25519 key cannot sign.
--
-- Nullable on purpose: existing installs have no signing key until they next
-- open the app. Clients treat "sender has no published key" as unverifiable,
-- and "sender HAS a key but sent an unsigned message" as invalid — which is
-- what closes the downgrade attack.

alter table public.device_keys
  add column if not exists signing_public_key text
    check (char_length(signing_public_key) <= 128);

-- No new policies needed and none wanted: device_keys already reads to any
-- authenticated user (you must be able to seal to, and verify, other members)
-- and writes only to `user_id = auth.uid()`. That existing write rule is what
-- stops anyone publishing a signing key on someone else's behalf, which would
-- let them forge that member's messages.

-- ============================================================
-- 20260730000007_join_hardening.sql
-- ============================================================

-- CommonGround — close the group self-join privilege escalation (ADR-36).
--
-- THE HOLE
-- --------
-- The original policy was:
--
--   create policy members_self_join on public.group_members
--     for insert to authenticated with check (user_id = auth.uid());
--
-- `role` and `state` have safe defaults ('member', 'pending'), but a column
-- default only applies when the column is OMITTED. The WITH CHECK constrained
-- `user_id` and nothing else, so any authenticated caller could simply supply
-- them:
--
--   POST /rest/v1/group_members
--   { "group_id": "<any public group>", "user_id": "<self>",
--     "role": "admin", "state": "active" }
--
-- That passes the check and lands an active admin row. `is_group_member()` and
-- `is_group_admin()` then return true, which unlocks the member roster, the
-- group's real-world pin coordinates, live invite codes, group renaming and
-- member deletion.
--
-- Reachable by anyone: the publishable key ships in the web bundle by design,
-- the app signs in anonymously on its own, and an anonymous Supabase session
-- holds the `authenticated` role — `to authenticated` is not a barrier. Public
-- group ids are enumerable through `groups_read` (visibility = 'public').
--
-- E2E encryption held: message bodies stay unreadable without an envelope
-- sealed to the attacker's X25519 key. Everything around them did not, and for
-- this threat model the roster IS the sensitive data.
--
-- THE FIX
-- -------
-- No client INSERT on group_members at all. Both legitimate paths become
-- SECURITY DEFINER functions, so the privileged write lives in one auditable
-- place instead of in a policy that has to enumerate what may not be set:
--
--   · creating a group  -> AFTER INSERT trigger seeds the creator
--   · joining a group   -> join_by_invite() validates the code, then inserts
--
-- Deny-by-default, as CONTEXT.md requires. Apply AFTER 20260725000002_groups.

-- ------------------------------------------------------- creator seeding

-- The creator must end up as the first active admin, but the client must not
-- be the one asserting that. A trigger cannot be skipped by a crafted request
-- the way a client-side insert can.
create or replace function public.seed_group_creator()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.group_members (group_id, user_id, role, state, joined_via)
  values (new.id, new.created_by, 'admin', 'active', 'creator')
  on conflict (group_id, user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists groups_seed_creator on public.groups;
create trigger groups_seed_creator
  after insert on public.groups
  for each row execute function public.seed_group_creator();

-- ------------------------------------------------------------ invite join

-- Validates the code and creates the PENDING row in one privileged step, so
-- the caller never touches group_members directly and cannot choose its own
-- role or state. Approval stays mandatory: this only ever writes 'pending'.
create or replace function public.join_by_invite(p_code text)
returns table(group_id uuid, group_name text)
language plpgsql security definer set search_path = public as $$
declare
  v_invite   public.group_invites%rowtype;
  v_group    public.groups%rowtype;
  v_existing public.group_members%rowtype;
  v_uid      uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'authentication required';
  end if;

  -- FOR UPDATE so two devices redeeming the last use cannot both win.
  select * into v_invite
  from public.group_invites
  where code = p_code
    and not revoked
    and expires_at > now()
    and uses < max_uses
  for update;

  if not found then
    raise exception 'invite is invalid, expired, or used up';
  end if;

  select * into v_group from public.groups where id = v_invite.group_id;

  select * into v_existing
  from public.group_members
  where public.group_members.group_id = v_invite.group_id
    and user_id = v_uid;

  -- A ban is not undone by finding another invite link.
  if found and v_existing.state = 'banned' then
    raise exception 'membership refused';
  end if;

  -- Idempotent: re-scanning the QR must not spend another use or duplicate
  -- the request. Only a genuinely new request consumes an invite use.
  if not found then
    insert into public.group_members
      (group_id, user_id, role, state, joined_via)
    values (v_invite.group_id, v_uid, 'member', 'pending', 'link');

    update public.group_invites
      set uses = uses + 1
      where id = v_invite.id;
  end if;

  return query select v_group.id, v_group.name;
end;
$$;

revoke execute on function public.join_by_invite from public, anon;
grant execute on function public.join_by_invite to authenticated;

-- --------------------------------------------------------------- the policy

-- Removed, not narrowed. A narrowed version would still be a policy whose
-- correctness depends on listing every column an attacker must not set, and
-- the next column added to this table would silently reopen the hole.
drop policy if exists members_self_join on public.group_members;
