#!/usr/bin/env bash
# Concatenate every migration, in order, into one file you can paste into the
# Supabase SQL Editor in a single go — including from a phone, where opening
# seven files and copying each one is the actual obstacle.
#
# Generated, never hand-edited: the migrations stay the single source of truth
# so the CLI path and the paste path can never disagree. Re-run this after
# adding a migration.
#
#   ./supabase/build_apply_all.sh
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=supabase/apply_all.sql

{
  echo "-- CommonGround — every migration, in order, as one script."
  echo "--"
  echo "-- GENERATED by supabase/build_apply_all.sh. Do not edit by hand;"
  echo "-- edit the migration and regenerate, or the two will drift apart."
  echo "--"
  echo "-- SAFE TO RUN MORE THAN ONCE. Every statement is idempotent"
  echo "-- (create ... if not exists / drop ... if exists / create or replace),"
  echo "-- so it does not matter which migrations your project already has."
  echo "-- Running it on a fully migrated project changes nothing."
  echo "--"
  echo "-- It does NOT run inside a single transaction: the Supabase SQL Editor"
  echo "-- wraps each statement itself. If it stops partway, fix the reported"
  echo "-- error and run the whole thing again — that is what idempotency buys."
  echo "--"
  echo "-- Generated from:"
  for f in supabase/migrations/*.sql; do echo "--   $(basename "$f")"; done
  echo

  for f in supabase/migrations/*.sql; do
    echo
    echo "-- ============================================================"
    echo "-- $(basename "$f")"
    echo "-- ============================================================"
    echo
    cat "$f"
  done
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines, $(du -h "$OUT" | cut -f1))"
